"""initial_models

Revision ID: 80efee000412
Revises: 
Create Date: 2026-06-17 15:23:21.522313+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80efee000412'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('action_code', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('authority', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'WARNING', 'FAILED', 'PENDING', name='action_status'), nullable=True),
    sa.Column('risk_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='risk_level'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_action_code'), 'action_logs', ['action_code'], unique=True)
    op.create_table('audit_protocols',
    sa.Column('audit_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.Enum('Financial', 'Operational', 'Regulatory', 'Security', name='audit_category'), nullable=False),
    sa.Column('status', sa.Enum('Passed', 'Warning', 'Pending', name='audit_status'), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_protocols_audit_code'), 'audit_protocols', ['audit_code'], unique=True)
    op.create_table('communications',
    sa.Column('comm_code', sa.String(length=30), nullable=False),
    sa.Column('sender', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('Directive', 'Inquiry', 'Emergency', name='comm_type'), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'RESPONDED', name='comm_status'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communications_comm_code'), 'communications', ['comm_code'], unique=True)
    op.create_table('departments',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_table('districts',
    sa.Column('district_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('governance_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('active_projects', sa.Integer(), nullable=True),
    sa.Column('completed_projects', sa.Integer(), nullable=True),
    sa.Column('delayed_projects', sa.Integer(), nullable=True),
    sa.Column('fund_utilization_pct', sa.Float(), nullable=True),
    sa.Column('pending_files', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('Optimal', 'Warning', 'Critical', name='district_status'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_district_code'), 'districts', ['district_code'], unique=True)
    op.create_table('department_district_data',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('funds_allocated', sa.BigInteger(), nullable=True),
    sa.Column('funds_released', sa.BigInteger(), nullable=True),
    sa.Column('funds_spent', sa.BigInteger(), nullable=True),
    sa.Column('total_projects', sa.Integer(), nullable=True),
    sa.Column('projects_completed', sa.Integer(), nullable=True),
    sa.Column('projects_delayed', sa.Integer(), nullable=True),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_district_data_department_id'), 'department_district_data', ['department_id'], unique=False)
    op.create_index(op.f('ix_department_district_data_district_id'), 'department_district_data', ['district_id'], unique=False)
    op.create_table('fund_allocations',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('fiscal_year', sa.String(length=20), nullable=False),
    sa.Column('allocated_cr', sa.Float(), nullable=True),
    sa.Column('spent_cr', sa.Float(), nullable=True),
    sa.Column('utilization_pct', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_allocations_department_id'), 'fund_allocations', ['department_id'], unique=False)
    op.create_table('officers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('resolved_files', sa.Integer(), nullable=True),
    sa.Column('avg_resolution_days', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('project_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('sector', sa.Enum('Infrastructure', 'Health', 'Education', 'Irrigation', 'Digital Gov', name='project_sector'), nullable=False),
    sa.Column('budget_cr', sa.Float(), nullable=True),
    sa.Column('spent_cr', sa.Float(), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('On Track', 'Delayed', 'Critical', name='project_status'), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('officers')
    op.drop_index(op.f('ix_fund_allocations_department_id'), table_name='fund_allocations')
    op.drop_table('fund_allocations')
    op.drop_index(op.f('ix_department_district_data_district_id'), table_name='department_district_data')
    op.drop_index(op.f('ix_department_district_data_department_id'), table_name='department_district_data')
    op.drop_table('department_district_data')
    op.drop_index(op.f('ix_districts_district_code'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_communications_comm_code'), table_name='communications')
    op.drop_table('communications')
    op.drop_index(op.f('ix_audit_protocols_audit_code'), table_name='audit_protocols')
    op.drop_table('audit_protocols')
    op.drop_index(op.f('ix_action_logs_action_code'), table_name='action_logs')
    op.drop_table('action_logs')
    # ### end Alembic commands ###
